# Generated by Django 3.2.7 on 2021-09-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0002_batch_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('topic_status', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed')], default='in progress', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.batch')),
            ],
        ),
    ]
