# Generated by Django 3.2.6 on 2021-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('copies', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
